return {
    { "folke/which-key.nvim", lazy=false },
    { 'nvim-lua/plenary.nvim' },
    { 'nvim-tree/nvim-tree.lua', lazy=false },
    { 'nvim-tree/nvim-web-devicons' },
    { 'nvim-treesitter/nvim-treesitter' },
    { 'danilamihailov/beacon.nvim' },
    { 'nvim-lualine/lualine.nvim' },
    { 'nvim-telescope/telescope.nvim', version = '0.1.1' },
    { 'voldikss/vim-floaterm' },
    { 'lukas-reineke/indent-blankline.nvim' },
    { 'BurntSushi/ripgrep' },
    { 'sharkdp/fd' },
    { 'kdheepak/lazygit.nvim' },
    { 'f-person/git-blame.nvim' },
    { "williamboman/mason.nvim" },
    { "williamboman/mason-lspconfig.nvim" },
    { "neovim/nvim-lspconfig" },
    { "sunjon/shade.nvim" },
    { "github/copilot.vim" },
    { "L3MON4D3/LuaSnip" },
    { 'kevinhwang91/nvim-ufo' },
    { 'princejoogie/dir-telescope.nvim' },
    { 'hrsh7th/cmp-nvim-lsp' },
    { 'hrsh7th/nvim-cmp' },
    { 'saadparwaiz1/cmp_luasnip' },
    { "0oAstro/dim.lua" },
    { "AckslD/nvim-neoclip.lua" },
}
